version: "3.8"

services:
  emqx:
    image: emqx/emqx:5.2.0
    container_name: transflow-mqtt
    ports:
      - "11883:11883"
      - "18083:18083"
      - "1883:1883"
      - "8083:8083"   
      - "8084:8084"
      - "8883:8883"
    volumes:
      - emqx-data:/opt/emqx
    networks:  
      transflow:
        aliases:
          - transflow.fhv.at
    env_file:
      - docker/runtime.env
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"] # check if EMQX is fully initialized (may take around 3 minutes)
      interval: 30s  # time between the completion of the last check and the next health check
      timeout: 100s   # maximum time for a check to complet (for some reason emqx ctl status regurarly takes upwards of 50s)
      start_period: 300s  # failing checks during this time will not be counted towards the max retries -> give container time to startup
      start_interval: 10s # time between health checks during startup period
      retries: 2  # number of failing checks to be counted as unhealthy

  influx-db:
    image: influxdb:2.7.1
    container_name: transflow-influx
    ports:
      - "8086:8086"
    volumes:
      - influx-data:/var/lib/influxdb2
      - influx-config:/etc/influxdb2
    networks:
      - transflow
    depends_on:
      emqx:
        condition: service_healthy
    env_file:
      - docker/runtime.env

  telegraf:
    image: telegraf:latest
    container_name: transflow-telegraf
    # wait for the MQTT service to fully initialize (setup its listener on port 1883) before starting telegraf
    # command: /etc/telegraf/wait-for-it.sh -t 0 transflow-mqtt:1883 -- telegraf
    ports:
      - "8092:8092"
      - "8094:8094"
      - "8125:8125"
    volumes:
      - telegraf-data:/etc/telegraf
    networks:  
      transflow:
        aliases:
          - transflow.fhv.at
    depends_on:
      emqx:
        condition: service_healthy
    env_file:
      - docker/runtime.env


volumes:
  emqx-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./docker/data/emqx

  influx-config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./docker/data/influx/config

  influx-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./docker/data/influx/db

  telegraf-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./docker/data/telegraf


networks:
  transflow:
    driver: bridge